initializr:
  types:
    - name: Maven Project
      id: maven-project
      description: Generate a Maven based project archive.
      tags:
        build: maven
        format: project
      default: true
      action: /starter.zip
  javaVersions:
    - id: 11
      default: false
    - id: 1.8
      default: true
  languages:
    - name: Java
      id: java
      default: true
    - name: Kotlin
      id: kotlin
      default: false
  packagings:
    - name: Jar
      id: jar
      default: true
    - name: War
      id: war
      default: false
  bootVersions:
    - name: Latest SNAPSHOT
      id: 2.2.0.BUILD-SNAPSHOT
      default: false
    - name: 2.1.1.
      id: 2.1.1.RELEASE
      default: true
  dependencies:
    - name: Tools
      content:
        - name: fastjson
          id: fastjson
          groupId: com.alibaba
          artifactId: fastjson
          version : 1.2.75
          description: 序列化工具
